# MoveIt default scalings (used when not set in code)
default_velocity_scaling_factor: 0.25
default_acceleration_scaling_factor: 0.20

joint_limits:
  # ── UR3e arm (actuated) ──────────────────────────────────────────────────────
  shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 3.141592653589793
    has_acceleration_limits: true
    max_acceleration: 3.0
    has_position_limits: true
    min_position: -3.141592653589793
    max_position:  3.141592653589793

  shoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 3.141592653589793
    has_acceleration_limits: true
    max_acceleration: 3.0
    has_position_limits: true
    min_position: -3.141592653589793
    max_position:  3.141592653589793

  elbow_joint:
    has_velocity_limits: true
    max_velocity: 3.141592653589793
    has_acceleration_limits: true
    max_acceleration: 3.0
    has_position_limits: true
    min_position: -3.141592653589793
    max_position:  3.141592653589793

  wrist_1_joint:
    has_velocity_limits: true
    max_velocity: 6.283185307179586
    has_acceleration_limits: true
    max_acceleration: 6.0
    has_position_limits: true
    min_position: -3.141592653589793
    max_position:  3.141592653589793

  wrist_2_joint:
    has_velocity_limits: true
    max_velocity: 6.283185307179586
    has_acceleration_limits: true
    max_acceleration: 6.0
    has_position_limits: true
    min_position: -3.141592653589793
    max_position:  3.141592653589793

  wrist_3_joint:
    has_velocity_limits: true
    max_velocity: 6.283185307179586
    has_acceleration_limits: true
    max_acceleration: 6.0
    has_position_limits: true
    min_position: -3.141592653589793
    max_position:  3.141592653589793

  # ── Robotiq 85 gripper ───────────────────────────────────────────────────────
  # Actuated joint (the only one that needs limits)
  robotiq_85_left_knuckle_joint:
    has_velocity_limits: true
    max_velocity: 0.6
    has_acceleration_limits: true
    max_acceleration: 1.0

  # The joints below are **mimics** of robotiq_85_left_knuckle_joint.
  # They are included for documentation; limits are disabled so they’re ignored.

  # mimic of left_knuckle (multiplier +1)
  robotiq_85_right_knuckle_joint:
    has_velocity_limits: false
    has_acceleration_limits: false
    has_position_limits: false  # mimic -> computed from driver/URDF, not commanded

  # mimic of left_knuckle (multiplier +1)
  robotiq_85_left_inner_knuckle_joint:
    has_velocity_limits: false
    has_acceleration_limits: false
    has_position_limits: false

  # mimic of left_knuckle (multiplier +1)
  robotiq_85_right_inner_knuckle_joint:
    has_velocity_limits: false
    has_acceleration_limits: false
    has_position_limits: false

  # mimic of left_knuckle (multiplier -1)
  robotiq_85_left_finger_tip_joint:
    has_velocity_limits: false
    has_acceleration_limits: false
    has_position_limits: false

  # mimic of left_knuckle (multiplier -1)
  robotiq_85_right_finger_tip_joint:
    has_velocity_limits: false
    has_acceleration_limits: false
    has_position_limits: false
