# Limits for the Pilz planner
cartesian_limits:
  max_trans_vel: 0.4      # 0.3–0.5 is a safe range
  max_trans_acc: 0.8      # 0.6–1.0 keeps motions smooth
  max_trans_dec: -1.6     # -1.2 to -2.0; less “brutal” stops than -5.0
  max_rot_vel: 1.57
